### ISSUE TITLE
Code execution issue

### ISSUE THREAD

**Issue by MikeModder** [MikeModder/ssmt#3]
Dropping `<script>process.exit()</script>` in a post causes the server actually exit. This is an issue with ejs, because it's taking this and running it on the server, which is obviously not good. Thankfully Artuto only did a process.exit() 😰

**Comment by MikeModder** [comment]
I am just an idiot, the issue was Artuto's user didn't have a profile object so the server crashed trying to use it

**Comment by Artuto** [comment]
Anyway i found an issue xd
